# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20160215_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pub_view',
            field=models.BooleanField(
                default=False, verbose_name=b'Reportable'),
        ),
    ]
