# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20160223_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualtime',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True),
        ),
    ]
