# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 15:52
from __future__ import unicode_literals

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    ActualTime = apps.get_model('main', 'ActualTime')
    # For now, only give unique ID's to my ActualTimes. Running
    # this over all 93,000 rows takes over a half hour.
    for row in ActualTime.objects.filter(user__username='njn2118'):
        row.uuid = uuid.uuid4()
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_actualtime_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
