# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20160309_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualtime',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
