# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20160309_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_column=b'assigned_to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_items', to='main.UserProfile'),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(blank=True, db_column=b'owner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_items', to='main.UserProfile'),
        ),
    ]
