# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20160330_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
    ]
