# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_auto_20160331_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_mod',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
