# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-09 12:01
from __future__ import unicode_literals
from django.db import migrations


def ensure_caretaker_in_personnel(p, w):
    if w.objects.filter(project=p,
                        user=p.caretaker_user).count() < 1:
        user = p.caretaker_user.userprofile
        w.objects.filter(project=p, user=user.user).delete()
        w.objects.create(project=p, auth="manager", user=user.user)


def update_caretaker_personnel(apps, schema_editor):
    Project = apps.get_model("main", "Project")
    WorksOn = apps.get_model("main", "WorksOn")
    for p in Project.objects.all():
        ensure_caretaker_in_personnel(p, WorksOn)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_projectpin'),
    ]

    operations = [
        migrations.RunPython(update_caretaker_personnel),
    ]
