# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-09 12:01
from __future__ import unicode_literals
from django.db import migrations


def update_caretaker_personnel(apps, schema_editor):
    Project = apps.get_model("main", "Project")
    for p in Project.objects.all():
        p.ensure_caretaker_in_personnel()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_projectpin'),
    ]

    operations = [
        migrations.RunPython(update_caretaker_personnel),
    ]
