# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_auto_20170731_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='internal',
            field=models.BooleanField(default=False),
        ),
    ]
