# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_auto_20180312_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Curriculum RFP', 'Curriculum RFP'), ('Funded', 'Funded'), ('Hybrid RFP', 'Hybrid RFP'), ('MOOC', 'MOOC'), ('Small RFP', 'Small RFP'), ('Strategic', 'Strategic'), ('Support', 'Support')], max_length=32, null=True, verbose_name='Project Category'),
        ),
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(help_text='This is the date that the project is completed and deployed.', null=True, verbose_name='Project Due Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='launch_date',
            field=models.DateField(blank=True, help_text='This is the date the project launches, eg. a MOOC launch.', null=True, verbose_name='Project Launch Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(help_text='This is the date that work starts.', null=True, verbose_name='Project Start Date'),
        ),
    ]
