# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_auto_20180312_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[(b'Admin', b'Admin'), (b'Curriculum RFP', b'Curriculum RFP'), (b'Funded', b'Funded'), (b'Hybrid RFP', b'Hybrid RFP'), (b'MOOC', b'MOOC'), (b'Small RFP', b'Small RFP'), (b'Strategic', b'Strategic'), (b'Support', b'Support')], max_length=32, null=True, verbose_name=b'Project Category'),
        ),
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(help_text=b'This is the date that the project is completed and deployed.', null=True, verbose_name=b'Project Due Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='launch_date',
            field=models.DateField(blank=True, help_text=b'This is the date the project launches, eg. a MOOC launch.', null=True, verbose_name=b'Project Launch Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(help_text=b'This is the date that work starts.', null=True, verbose_name=b'Project Start Date'),
        ),
    ]
