# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_auto_20180322_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(blank=True, help_text=b'This is the date that the project is completed and deployed.', null=True, verbose_name=b'Project Due Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text=b'This is the date that work starts.', null=True, verbose_name=b'Project Start Date'),
        ),
    ]
