# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 19:46
from __future__ import unicode_literals

from datetime import timedelta
from django.db import migrations
from django.db.models import Q


def find_first_item(milestones):
    """
    Return the first item, chronologically, in this set of milestones.

    Returns None if there are no items.
    """
    for milestone in milestones:
        for item in milestone.item_set.order_by('target_date'):
            return item

    return None


def update_project_dates(apps, schema_editor):
    Project = apps.get_model('main', 'Project')

    for project in Project.objects.all():
        milestones = project.milestone_set.filter(
            ~Q(name='Someday/Maybe')
        ).order_by('target_date')
        last_milestone = milestones.last()

        # Guess the project's start date by using the first
        # milestone's first task's target date, minus 7 days.
        first_item = find_first_item(milestones)

        save = False

        if not project.start_date and \
           first_item and first_item.target_date:
            project.start_date = first_item.target_date - timedelta(days=7)
            save = True

        if not project.due_date and \
           last_milestone and last_milestone.target_date:
            project.due_date = last_milestone.target_date
            save = True

        if save:
            project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_auto_20180327_1233'),
    ]

    operations = [
        migrations.RunPython(update_project_dates),
    ]
