# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 14:17
from __future__ import unicode_literals

from django.db import migrations


def init_project_manager(apps, schema_editor):
    Project = apps.get_model("main", "Project")
    for project in Project.objects.all():
        project.project_manager_user = project.caretaker_user
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_project_project_manager_user'),
    ]

    operations = [
         migrations.RunPython(init_project_manager),
    ]
