# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_auto_20180418_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Curriculum RFP', 'Curriculum RFP'), ('Funded', 'Funded'), ('Hybrid RFP', 'Hybrid RFP'), ('MOOC', 'MOOC'), ('Research & Analysis', 'Research & Analysis'), ('Small RFP', 'Small RFP'), ('Strategic', 'Strategic'), ('Support', 'Support')], max_length=32, null=True, verbose_name='Category'),
        ),
    ]
