# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_auto_20180418_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[(b'New', b'New'), (b'Development', b'Development'), (b'Deployment', b'Deployment'), (b'Defunct', b'Defunct'), (b'Deferred', b'Deferred'), (b'Non-project', b'Non-project'), (b'Archived', b'Archived')], default=b'New', max_length=16),
        ),
    ]
