# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_auto_20180418_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Development', 'Development'), ('Deployment', 'Deployment'), ('Defunct', 'Defunct'), ('Deferred', 'Deferred'), ('Non-project', 'Non-project'), ('Archived', 'Archived')], default='New', max_length=16),
        ),
    ]
