# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 14:52
from __future__ import unicode_literals

from django.db import migrations


def update_projects(apps, schema_editor):
    Project = apps.get_model('main', 'Project')
    for project in Project.objects.filter(status='Defunct'):
        project.status = 'Archived'
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_auto_20181012_1630'),
    ]

    operations = [
        migrations.RunPython(update_projects)
    ]
