# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_auto_20181016_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[(b'New', b'New'), (b'Development', b'Development'), (b'Deployment', b'Deployment'), (b'Defunct', b'Defunct'), (b'Deferred', b'Deferred'), (b'Non-project', b'Non-project'), (b'Archived', b'Archived'), (b'MigratedToJira', b'MigratedToJira')], default=b'New', max_length=16),
        ),
    ]
