# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_auto_20181016_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Development', 'Development'), ('Deployment', 'Deployment'), ('Defunct', 'Defunct'), ('Deferred', 'Deferred'), ('Non-project', 'Non-project'), ('Archived', 'Archived'), ('MigratedToJira', 'MigratedToJira')], default='New', max_length=16),
        ),
    ]
