language: python
sudo: false
addons:
  postgresql: "9.3"
  firefox: "42.0"
python:
  - "2.7"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - ./bootstrap.py
before_script:
  - psql -c 'create database ci_test;' -U postgres
script:
  - make travis
  - make behave
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
