language: python
dist: trusty
sudo: false
addons:
  postgresql: "9.6"
python:
  - "2.7"
before_script:
  - psql -c 'create database ci_test;' -U postgres
script:
  - make flake8
  - make travis
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
