language: python
dist: bionic
addons:
  postgresql: "10"
python:
  - "3.6"
before_script:
  - psql -c 'create database ci_test;' -U postgres
  - npm install --upgrade npm
script:
  - make flake8
  - make travis
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
