db:
  image: postgres
rabbitmq:
  image: rabbitmq
web:
  image: ccnmtl/dmt
  command: manage runserver 0.0.0.0:8000
  environment:
    - SETTINGS=settings_compose
  volumes:
    - .:/var/www/dmt/dmt
  ports:
    - "8000:8000"
  links:
    - db
    - rabbitmq
celery:
  image: ccnmtl/dmt
  command: worker
  environment:
    - SETTINGS=settings_compose
    - C_FORCE_ROOT=true
  volumes:
    - .:/var/www/dmt/dmt
  links:
    - db
    - rabbitmq

beat:
  image: ccnmtl/dmt
  command: beat
  environment:
    - SETTINGS=settings_compose    
    - C_FORCE_ROOT=true
  volumes:
    - .:/var/www/dmt/dmt
  links:
    - db
    - rabbitmq
