import django.views.static
from django.urls import path, re_path, include
from django.contrib import admin
from django.conf import settings
from django.views.generic import TemplateView
from django_cas_ng import views as cas_views


from dmt.main.views import (
    AddTrackersView, SearchView,
    ActualTimeDeleteView,
    AddCommentView, CommentUpdateView, CommentDeleteView, ResolveItemView,
    InProgressItemView, VerifyItemView, ReopenItemView,
    SplitItemView, ItemDetailView,
    IndexView, ClientListView, AddClientView,
    ClientDetailView, ForumView, GroupDetailView, GroupListView,
    NodeDetailView, MilestoneDetailView,
    ProjectListView, MyProjectListView, ProjectDetailView,
    ProjectTimeLineView, ProjectTagListView, ProjectTagView,
    UserTimeLineView,
    UserListView, UserDetailView, NodeReplyView, ProjectAddTodoView,
    ProjectAddNodeView, TagItemView, RemoveTagFromItemView,
    TagNodeView, RemoveTagFromNodeView, DeleteTagView,
    TagDetailView, TagListView, ItemPriorityView, ReassignItemView,
    ChangeOwnerItemView, ProjectAddStatusUpdateView,
    StatusUpdateListView, StatusUpdateUpdateView, StatusUpdateDeleteView,
    NodeUpdateView, NodeDeleteView, UserUpdateView,
    ProjectCreateView, ProjectUpdateView, MilestoneUpdateView,
    ItemCreateView, BugCreateView, ItemUpdateView,
    ProjectAddItemView, DashboardView, MilestoneListView,
    ProjectRemoveUserView, ProjectAddPersonnelView, ProjectAddMilestoneView,
    ItemDeleteView, SignS3View, ItemAddAttachmentView,
    DeleteAttachmentView, GroupCreateView,
    DeactivateUserView, ItemMoveProjectView, RemoveUserFromGroupView,
    AddUserToGroupView, MilestoneDeleteView, OwnedItemsView,
    ItemSetMilestoneView, MergeTagView, ItemAddSubscriberView,
    ProjectPinView,
)
from dmt.main.feeds import ForumFeed, StatusUpdateFeed, ProjectFeed


urlpatterns = [
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    path('cas/login', cas_views.LoginView.as_view(),
         name='cas_ng_login'),
    path('cas/logout', cas_views.LogoutView.as_view(),
         name='cas_ng_logout'),
    re_path(r'^$', IndexView.as_view()),
    re_path(r'^admin/', admin.site.urls),
    re_path(
        r'^add_trackers/$', AddTrackersView.as_view(), name='add_trackers'),
    re_path(r'^api/1.0/', include('dmt.api.urls')),
    re_path(r'^actualtime/(?P<uuid>[^/]+)/delete/$',
            ActualTimeDeleteView.as_view(),
            name='delete_time'),
    re_path(r'^drf/', include('dmt.api.urls')),
    re_path(r'^oauth2/', include('oauth2_provider.urls', namespace='oauth2')),
    re_path(r'^search/$', SearchView.as_view()),
    re_path(r'^client/$', ClientListView.as_view()),
    re_path(r'^client/(?P<pk>\d+)/$', ClientDetailView.as_view(),
            name="client_detail"),
    re_path(r'^client/add/$', AddClientView.as_view(), name='add_client'),
    re_path(r'^sign_s3/$', SignS3View.as_view()),
    re_path(r'^forum/$', ForumView.as_view(), name='forum_list'),
    re_path(r'^forum/(?P<pk>\d+)/$', NodeDetailView.as_view()),
    re_path(r'^forum/(?P<pk>\d+)/reply/$', NodeReplyView.as_view()),
    re_path(r'^forum/(?P<pk>\d+)/tag/$', TagNodeView.as_view()),
    re_path(r'^forum/(?P<pk>\d+)/remove_tag/(?P<slug>[^/]+)/$',
            RemoveTagFromNodeView.as_view()),
    re_path(r'^forum/(?P<pk>\d+)/edit/$', NodeUpdateView.as_view()),
    re_path(r'^forum/(?P<pk>\d+)/delete/$', NodeDeleteView.as_view()),
    re_path(
        r'^group/create/$', GroupCreateView.as_view(), name='group_create'),
    re_path(r'^group/$', GroupListView.as_view(), name='group_list'),
    re_path(r'^group/(?P<pk>\w+)/$', GroupDetailView.as_view(),
            name='group_detail'),
    re_path(
        r'^group/(?P<pk>\w+)/remove_user/$', RemoveUserFromGroupView.as_view(),
        name='remove_user_from_group'),
    re_path(r'^group/(?P<pk>\w+)/add_user/$', AddUserToGroupView.as_view(),
            name='add_user_to_group'),
    re_path(r'^item/create/$', ItemCreateView.as_view(), name='item_create'),
    re_path(r'^bug/create/$', BugCreateView.as_view(), name='bug_create'),
    re_path(
        r'^item/(?P<pk>\d+)/$', ItemDetailView.as_view(), name='item_detail'),
    re_path(r'^item/(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(),
            name='item_update'),
    re_path(r'^item/(?P<pk>\d+)/move_project/$', ItemMoveProjectView.as_view(),
            name='item-move-project'),
    re_path(r'^item/(?P<pk>\d+)/comment/$', AddCommentView.as_view()),
    re_path(r'^comment/(?P<pk>\d+)/update/$', CommentUpdateView.as_view(),
            name='comment_update'),
    re_path(r'^comment/(?P<pk>\d+)/delete/$', CommentDeleteView.as_view(),
            name='comment_delete'),
    re_path(r'^item/(?P<pk>\d+)/resolve/$', ResolveItemView.as_view()),
    re_path(r'^item/(?P<pk>\d+)/inprogress/$', InProgressItemView.as_view()),
    re_path(r'^item/(?P<pk>\d+)/verify/$', VerifyItemView.as_view()),
    re_path(r'^item/(?P<pk>\d+)/reopen/$', ReopenItemView.as_view()),
    re_path(r'^item/(?P<pk>\d+)/split/$', SplitItemView.as_view()),
    re_path(r'^item/(?P<pk>\d+)/tag/$', TagItemView.as_view()),
    re_path(r'^item/(?P<pk>\d+)/set_milestone/$',
            ItemSetMilestoneView.as_view(), name='set_item_milestone'),
    re_path(r'^item/(?P<pk>\d+)/remove_tag/(?P<slug>[^/]+)/$',
            RemoveTagFromItemView.as_view()),
    re_path(r'^item/(?P<pk>\d+)/priority/(?P<priority>\d)/$',
            ItemPriorityView.as_view()),
    re_path(r'^item/(?P<pk>\d+)/assigned_to/$', ReassignItemView.as_view()),
    re_path(r'^item/(?P<pk>\d+)/owner/$', ChangeOwnerItemView.as_view()),
    re_path(r'^item/(?P<pk>\d+)/delete/$', ItemDeleteView.as_view()),
    re_path(r'^item/(?P<pk>\d+)/add_attachment/$',
            ItemAddAttachmentView.as_view()),
    re_path(
        r'^attachment/(?P<pk>\d+)/delete/$', DeleteAttachmentView.as_view(),
        name="delete_attachment"),
    re_path(r'^item/(?P<pk>\d+)/add_subscriber/$',
            ItemAddSubscriberView.as_view(),
            name='add_subscriber'),
    re_path(r'^milestone/$', MilestoneListView.as_view()),
    re_path(r'^milestone/(?P<pk>\d+)/$', MilestoneDetailView.as_view(),
            name='milestone_detail'),
    re_path(r'^milestone/(?P<pk>\d+)/edit/$', MilestoneUpdateView.as_view()),
    re_path(r'^milestone/(?P<pk>\d+)/delete/$', MilestoneDeleteView.as_view(),
            name="delete_milestone"),
    re_path(r'^project/$', ProjectListView.as_view(), name='project_list'),
    re_path(r'^my_projects/$', MyProjectListView.as_view(),
            name='my_project_list'),
    re_path(r'^project/create/$', ProjectCreateView.as_view(),
            name='project_create'),
    re_path(r'^project/(?P<pk>\d+)/$', ProjectDetailView.as_view(),
            name='project_detail'),
    re_path(r'^project/(?P<pk>\d+)/pin/$', ProjectPinView.as_view(),
            name='project-pin'),
    re_path(r'^project/(?P<pk>\d+)/board/$', ProjectDetailView.as_view(
        template_name="main/project_board.html"),
            name='project_board'),
    re_path(r'^project/(?P<pk>\d+)/kanban/$', ProjectDetailView.as_view(
        template_name="main/project_kanban.html"),
            name='project_kanban'),
    re_path(r'^project/(?P<pk>\d+)/timeline/$', ProjectTimeLineView.as_view(),
            name='project_timeline'),
    re_path(r'^project/(?P<pk>\d+)/add_bug/$',
            ProjectAddItemView.as_view(item_type='bug')),
    re_path(r'^project/(?P<pk>\d+)/add_action_item/$',
            ProjectAddItemView.as_view(item_type='action item'),
            name='add_action_item'),
    re_path(r'^project/(?P<pk>\d+)/add_todo/$', ProjectAddTodoView.as_view(),
            name='project_add_todo'),
    re_path(r'^project/(?P<pk>\d+)/add_node/$', ProjectAddNodeView.as_view(),
            name='project_add_node'),
    re_path(r'^project/(?P<pk>\d+)/add_milestone/$',
            ProjectAddMilestoneView.as_view()),
    re_path(r'^project/(?P<pk>\d+)/add_update/$',
            ProjectAddStatusUpdateView.as_view(), name='project_add_update'),
    re_path(r'^project/(?P<pk>\d+)/edit/$', ProjectUpdateView.as_view()),
    re_path(r'^project/(?P<pk>\d+)/remove_user/(?P<username>\w+)/$',
            ProjectRemoveUserView.as_view()),
    re_path(r'^project/(?P<pk>\d+)/add_personnel/$',
            ProjectAddPersonnelView.as_view()),
    re_path(r'^project/(?P<pk>\d+)/tag/$', ProjectTagListView.as_view(),
            name='project_tag_list'),
    re_path(r'^project/(?P<pk>\d+)/tag/(?P<slug>[^/]+)/$',
            ProjectTagView.as_view(),
            name='project_tag'),

    re_path(r'^status/$', StatusUpdateListView.as_view()),
    re_path(r'^status/(?P<pk>\d+)/$', StatusUpdateUpdateView.as_view()),
    re_path(r'^status/(?P<pk>\d+)/delete/$', StatusUpdateDeleteView.as_view()),
    re_path(r'^report/', include('dmt.report.urls')),
    re_path(r'^user/$', UserListView.as_view(), name='user_list'),
    re_path(
        r'^user/(?P<pk>\w+)/$', UserDetailView.as_view(), name='user_detail'),
    re_path(r'^user/(?P<pk>\w+)/deactivate/$', DeactivateUserView.as_view(),
            name='user_deactivate'),
    re_path(r'^user/(?P<pk>\w+)/edit/$', UserUpdateView.as_view(),
            name='user_edit'),
    re_path(r'^user/(?P<pk>\w+)/owned/$', OwnedItemsView.as_view(),
            name='owned_items'),
    re_path(r'^user/(?P<pk>\w+)/timeline/$', UserTimeLineView.as_view(),
            name='user_timeline'),
    re_path(r'^tag/$', TagListView.as_view(), name='tag_list'),
    re_path(
        r'^tag/(?P<slug>[^/]+)/$', TagDetailView.as_view(), name='tag_detail'),
    re_path(r'^tag/(?P<slug>[^/]+)/merge/$', MergeTagView.as_view(),
            name='merge_tag'),
    re_path(r'^tag/(?P<slug>[^/]+)/delete/$', DeleteTagView.as_view(),
            name="delete_tag"),
    re_path(
        r'^dashboard/$', DashboardView.as_view(), name='project_dashboard'),
    re_path(r'^feeds/forum/rss/$', ForumFeed(), name='forum_feed'),
    re_path(
        r'^feeds/status/$', StatusUpdateFeed(), name='status_feed'),
    re_path(
        r'^feeds/project/(?P<pk>\d+)/$', ProjectFeed(), name='project_feed'),
    re_path(r'^_impersonate/', include('impersonate.urls')),
    re_path(r'^stats/$', TemplateView.as_view(template_name="stats.html")),
    re_path(r'^smoketest/', include('smoketest.urls')),
    re_path(
        r'^uploads/(?P<path>.*)$',
        django.views.static.serve, {'document_root': settings.MEDIA_ROOT}),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ]

handler500 = 'dmt.main.views.server_error'
